TOS = $(shell ncc -print-tosdir)

# Top-level Makefile for tools/java 

#ROOT = ../../../../../..
#ROOT = $(TOS)/../tools/java
ROOT = $(TOS)/../support/sdk/java
include $(ROOT)/Makefile.include



