# Top-level Makefile for tools/java 
TOS = $(shell ncc -print-tosdir)

SUBDIRS = agentInjector remoteTupleSpace

#ROOT = ../../../../..
#ROOT = $(TOS)/../tools/java
ROOT = $(TOS)/../support/sdk/java

include $(ROOT)/Makefile.include

