includes SpaceLocalizer;

/**
 * Tests the SpaceLocalizer.  Listens for events generated by it.
 *
 * @author Chien-Liang Fok
 */
configuration SpaceLocalizerTester {
}
implementation {
  components Main, SpaceLocalizerTesterM as Tester, SpaceLocalizerC;
  components GenericComm as Comm, LedsC;
  components CC1000RadioC;
  
  Main.StdControl -> Tester;   
  Main.StdControl -> Comm;
  Main.StdControl -> CC1000RadioC;
  
  Tester.SpaceLocalizerI -> SpaceLocalizerC;  
  Tester.Leds -> LedsC;
  Tester.SendMsg -> Comm.SendMsg[1];
  Tester.CC1000Control -> CC1000RadioC;
  Tester.RadioControl -> CC1000RadioC;
}

