/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'AgillaRxnMsg'
 * message type.
 */

package agilla.messages;

public class AgillaRxnMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 28;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 20;

    /** Create a new AgillaRxnMsg of size 28. */
    public AgillaRxnMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new AgillaRxnMsg of the given data_length. */
    public AgillaRxnMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AgillaRxnMsg with the given data_length
     * and base offset.
     */
    public AgillaRxnMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AgillaRxnMsg using the given byte array
     * as backing store.
     */
    public AgillaRxnMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AgillaRxnMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public AgillaRxnMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AgillaRxnMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public AgillaRxnMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AgillaRxnMsg embedded in the given message
     * at the given base offset.
     */
    public AgillaRxnMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AgillaRxnMsg embedded in the given message
     * at the given base offset and length.
     */
    public AgillaRxnMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <AgillaRxnMsg> \n";
      try {
        s += "  [msgNum=0x"+Long.toHexString(get_msgNum())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [rxn.id.id=0x"+Long.toHexString(get_rxn_id_id())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [rxn.pc=0x"+Long.toHexString(get_rxn_pc())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [rxn.template.flags=0x"+Long.toHexString(get_rxn_template_flags())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [rxn.template.size=0x"+Long.toHexString(get_rxn_template_size())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [rxn.template.data=";
        for (int i = 0; i < 20; i++) {
          s += "0x"+Long.toHexString(getElement_rxn_template_data(i) & 0xff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: msgNum
    //   Field type: int
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'msgNum' is signed (false).
     */
    public static boolean isSigned_msgNum() {
        return false;
    }

    /**
     * Return whether the field 'msgNum' is an array (false).
     */
    public static boolean isArray_msgNum() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'msgNum'
     */
    public static int offset_msgNum() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'msgNum'
     */
    public static int offsetBits_msgNum() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'msgNum'
     */
    public int get_msgNum() {
        return (int)getUIntBEElement(offsetBits_msgNum(), 16);
    }

    /**
     * Set the value of the field 'msgNum'
     */
    public void set_msgNum(int value) {
        setUIntBEElement(offsetBits_msgNum(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'msgNum'
     */
    public static int size_msgNum() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'msgNum'
     */
    public static int sizeBits_msgNum() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: rxn.id.id
    //   Field type: int
    //   Offset (bits): 16
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'rxn.id.id' is signed (false).
     */
    public static boolean isSigned_rxn_id_id() {
        return false;
    }

    /**
     * Return whether the field 'rxn.id.id' is an array (false).
     */
    public static boolean isArray_rxn_id_id() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'rxn.id.id'
     */
    public static int offset_rxn_id_id() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'rxn.id.id'
     */
    public static int offsetBits_rxn_id_id() {
        return 16;
    }

    /**
     * Return the value (as a int) of the field 'rxn.id.id'
     */
    public int get_rxn_id_id() {
        return (int)getUIntBEElement(offsetBits_rxn_id_id(), 16);
    }

    /**
     * Set the value of the field 'rxn.id.id'
     */
    public void set_rxn_id_id(int value) {
        setUIntBEElement(offsetBits_rxn_id_id(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'rxn.id.id'
     */
    public static int size_rxn_id_id() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'rxn.id.id'
     */
    public static int sizeBits_rxn_id_id() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: rxn.pc
    //   Field type: int
    //   Offset (bits): 32
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'rxn.pc' is signed (false).
     */
    public static boolean isSigned_rxn_pc() {
        return false;
    }

    /**
     * Return whether the field 'rxn.pc' is an array (false).
     */
    public static boolean isArray_rxn_pc() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'rxn.pc'
     */
    public static int offset_rxn_pc() {
        return (32 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'rxn.pc'
     */
    public static int offsetBits_rxn_pc() {
        return 32;
    }

    /**
     * Return the value (as a int) of the field 'rxn.pc'
     */
    public int get_rxn_pc() {
        return (int)getUIntBEElement(offsetBits_rxn_pc(), 16);
    }

    /**
     * Set the value of the field 'rxn.pc'
     */
    public void set_rxn_pc(int value) {
        setUIntBEElement(offsetBits_rxn_pc(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'rxn.pc'
     */
    public static int size_rxn_pc() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'rxn.pc'
     */
    public static int sizeBits_rxn_pc() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: rxn.template.flags
    //   Field type: short
    //   Offset (bits): 48
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'rxn.template.flags' is signed (false).
     */
    public static boolean isSigned_rxn_template_flags() {
        return false;
    }

    /**
     * Return whether the field 'rxn.template.flags' is an array (false).
     */
    public static boolean isArray_rxn_template_flags() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'rxn.template.flags'
     */
    public static int offset_rxn_template_flags() {
        return (48 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'rxn.template.flags'
     */
    public static int offsetBits_rxn_template_flags() {
        return 48;
    }

    /**
     * Return the value (as a short) of the field 'rxn.template.flags'
     */
    public short get_rxn_template_flags() {
        return (short)getUIntBEElement(offsetBits_rxn_template_flags(), 8);
    }

    /**
     * Set the value of the field 'rxn.template.flags'
     */
    public void set_rxn_template_flags(short value) {
        setUIntBEElement(offsetBits_rxn_template_flags(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'rxn.template.flags'
     */
    public static int size_rxn_template_flags() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'rxn.template.flags'
     */
    public static int sizeBits_rxn_template_flags() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: rxn.template.size
    //   Field type: short
    //   Offset (bits): 56
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'rxn.template.size' is signed (false).
     */
    public static boolean isSigned_rxn_template_size() {
        return false;
    }

    /**
     * Return whether the field 'rxn.template.size' is an array (false).
     */
    public static boolean isArray_rxn_template_size() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'rxn.template.size'
     */
    public static int offset_rxn_template_size() {
        return (56 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'rxn.template.size'
     */
    public static int offsetBits_rxn_template_size() {
        return 56;
    }

    /**
     * Return the value (as a short) of the field 'rxn.template.size'
     */
    public short get_rxn_template_size() {
        return (short)getUIntBEElement(offsetBits_rxn_template_size(), 8);
    }

    /**
     * Set the value of the field 'rxn.template.size'
     */
    public void set_rxn_template_size(short value) {
        setUIntBEElement(offsetBits_rxn_template_size(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'rxn.template.size'
     */
    public static int size_rxn_template_size() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'rxn.template.size'
     */
    public static int sizeBits_rxn_template_size() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: rxn.template.data
    //   Field type: short[]
    //   Offset (bits): 64
    //   Size of each element (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'rxn.template.data' is signed (false).
     */
    public static boolean isSigned_rxn_template_data() {
        return false;
    }

    /**
     * Return whether the field 'rxn.template.data' is an array (true).
     */
    public static boolean isArray_rxn_template_data() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'rxn.template.data'
     */
    public static int offset_rxn_template_data(int index1) {
        int offset = 64;
        if (index1 < 0 || index1 >= 20) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'rxn.template.data'
     */
    public static int offsetBits_rxn_template_data(int index1) {
        int offset = 64;
        if (index1 < 0 || index1 >= 20) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return offset;
    }

    /**
     * Return the entire array 'rxn.template.data' as a short[]
     */
    public short[] get_rxn_template_data() {
        short[] tmp = new short[20];
        for (int index0 = 0; index0 < numElements_rxn_template_data(0); index0++) {
            tmp[index0] = getElement_rxn_template_data(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'rxn.template.data' from the given short[]
     */
    public void set_rxn_template_data(short[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_rxn_template_data(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a short) of the array 'rxn.template.data'
     */
    public short getElement_rxn_template_data(int index1) {
        return (short)getUIntBEElement(offsetBits_rxn_template_data(index1), 8);
    }

    /**
     * Set an element of the array 'rxn.template.data'
     */
    public void setElement_rxn_template_data(int index1, short value) {
        setUIntBEElement(offsetBits_rxn_template_data(index1), 8, value);
    }

    /**
     * Return the total size, in bytes, of the array 'rxn.template.data'
     */
    public static int totalSize_rxn_template_data() {
        return (160 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'rxn.template.data'
     */
    public static int totalSizeBits_rxn_template_data() {
        return 160;
    }

    /**
     * Return the size, in bytes, of each element of the array 'rxn.template.data'
     */
    public static int elementSize_rxn_template_data() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'rxn.template.data'
     */
    public static int elementSizeBits_rxn_template_data() {
        return 8;
    }

    /**
     * Return the number of dimensions in the array 'rxn.template.data'
     */
    public static int numDimensions_rxn_template_data() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'rxn.template.data'
     */
    public static int numElements_rxn_template_data() {
        return 20;
    }

    /**
     * Return the number of elements in the array 'rxn.template.data'
     * for the given dimension.
     */
    public static int numElements_rxn_template_data(int dimension) {
      int array_dims[] = { 20,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /**
     * Fill in the array 'rxn.template.data' with a String
     */
    public void setString_rxn_template_data(String s) { 
         int len = s.length();
         int i;
         for (i = 0; i < len; i++) {
             setElement_rxn_template_data(i, (short)s.charAt(i));
         }
         setElement_rxn_template_data(i, (short)0); //null terminate
    }

    /**
     * Read the array 'rxn.template.data' as a String
     */
    public String getString_rxn_template_data() { 
         char carr[] = new char[Math.min(net.tinyos.message.Message.MAX_CONVERTED_STRING_LENGTH,20)];
         int i;
         for (i = 0; i < carr.length; i++) {
             if ((char)getElement_rxn_template_data(i) == (char)0) break;
             carr[i] = (char)getElement_rxn_template_data(i);
         }
         return new String(carr,0,i);
    }

}
