/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'AgillaNbrMsg'
 * message type.
 */

package agilla.messages;

public class AgillaNbrMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 24;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 39;

    /** Create a new AgillaNbrMsg of size 24. */
    public AgillaNbrMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new AgillaNbrMsg of the given data_length. */
    public AgillaNbrMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AgillaNbrMsg with the given data_length
     * and base offset.
     */
    public AgillaNbrMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AgillaNbrMsg using the given byte array
     * as backing store.
     */
    public AgillaNbrMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AgillaNbrMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public AgillaNbrMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AgillaNbrMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public AgillaNbrMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AgillaNbrMsg embedded in the given message
     * at the given base offset.
     */
    public AgillaNbrMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AgillaNbrMsg embedded in the given message
     * at the given base offset and length.
     */
    public AgillaNbrMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <AgillaNbrMsg> \n";
      try {
        s += "  [hopsToGW=";
        for (int i = 0; i < 4; i++) {
          s += "0x"+Long.toHexString(getElement_hopsToGW(i) & 0xffff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [nbr=";
        for (int i = 0; i < 4; i++) {
          s += "0x"+Long.toHexString(getElement_nbr(i) & 0xffff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [lqi=";
        for (int i = 0; i < 4; i++) {
          s += "0x"+Long.toHexString(getElement_lqi(i) & 0xffff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: hopsToGW
    //   Field type: int[], unsigned
    //   Offset (bits): 0
    //   Size of each element (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'hopsToGW' is signed (false).
     */
    public static boolean isSigned_hopsToGW() {
        return false;
    }

    /**
     * Return whether the field 'hopsToGW' is an array (true).
     */
    public static boolean isArray_hopsToGW() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'hopsToGW'
     */
    public static int offset_hopsToGW(int index1) {
        int offset = 0;
        if (index1 < 0 || index1 >= 4) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'hopsToGW'
     */
    public static int offsetBits_hopsToGW(int index1) {
        int offset = 0;
        if (index1 < 0 || index1 >= 4) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return offset;
    }

    /**
     * Return the entire array 'hopsToGW' as a int[]
     */
    public int[] get_hopsToGW() {
        int[] tmp = new int[4];
        for (int index0 = 0; index0 < numElements_hopsToGW(0); index0++) {
            tmp[index0] = getElement_hopsToGW(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'hopsToGW' from the given int[]
     */
    public void set_hopsToGW(int[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_hopsToGW(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a int) of the array 'hopsToGW'
     */
    public int getElement_hopsToGW(int index1) {
        return (int)getUIntBEElement(offsetBits_hopsToGW(index1), 16);
    }

    /**
     * Set an element of the array 'hopsToGW'
     */
    public void setElement_hopsToGW(int index1, int value) {
        setUIntBEElement(offsetBits_hopsToGW(index1), 16, value);
    }

    /**
     * Return the total size, in bytes, of the array 'hopsToGW'
     */
    public static int totalSize_hopsToGW() {
        return (64 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'hopsToGW'
     */
    public static int totalSizeBits_hopsToGW() {
        return 64;
    }

    /**
     * Return the size, in bytes, of each element of the array 'hopsToGW'
     */
    public static int elementSize_hopsToGW() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'hopsToGW'
     */
    public static int elementSizeBits_hopsToGW() {
        return 16;
    }

    /**
     * Return the number of dimensions in the array 'hopsToGW'
     */
    public static int numDimensions_hopsToGW() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'hopsToGW'
     */
    public static int numElements_hopsToGW() {
        return 4;
    }

    /**
     * Return the number of elements in the array 'hopsToGW'
     * for the given dimension.
     */
    public static int numElements_hopsToGW(int dimension) {
      int array_dims[] = { 4,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: nbr
    //   Field type: int[], unsigned
    //   Offset (bits): 64
    //   Size of each element (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'nbr' is signed (false).
     */
    public static boolean isSigned_nbr() {
        return false;
    }

    /**
     * Return whether the field 'nbr' is an array (true).
     */
    public static boolean isArray_nbr() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'nbr'
     */
    public static int offset_nbr(int index1) {
        int offset = 64;
        if (index1 < 0 || index1 >= 4) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'nbr'
     */
    public static int offsetBits_nbr(int index1) {
        int offset = 64;
        if (index1 < 0 || index1 >= 4) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return offset;
    }

    /**
     * Return the entire array 'nbr' as a int[]
     */
    public int[] get_nbr() {
        int[] tmp = new int[4];
        for (int index0 = 0; index0 < numElements_nbr(0); index0++) {
            tmp[index0] = getElement_nbr(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'nbr' from the given int[]
     */
    public void set_nbr(int[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_nbr(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a int) of the array 'nbr'
     */
    public int getElement_nbr(int index1) {
        return (int)getUIntBEElement(offsetBits_nbr(index1), 16);
    }

    /**
     * Set an element of the array 'nbr'
     */
    public void setElement_nbr(int index1, int value) {
        setUIntBEElement(offsetBits_nbr(index1), 16, value);
    }

    /**
     * Return the total size, in bytes, of the array 'nbr'
     */
    public static int totalSize_nbr() {
        return (64 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'nbr'
     */
    public static int totalSizeBits_nbr() {
        return 64;
    }

    /**
     * Return the size, in bytes, of each element of the array 'nbr'
     */
    public static int elementSize_nbr() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'nbr'
     */
    public static int elementSizeBits_nbr() {
        return 16;
    }

    /**
     * Return the number of dimensions in the array 'nbr'
     */
    public static int numDimensions_nbr() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'nbr'
     */
    public static int numElements_nbr() {
        return 4;
    }

    /**
     * Return the number of elements in the array 'nbr'
     * for the given dimension.
     */
    public static int numElements_nbr(int dimension) {
      int array_dims[] = { 4,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: lqi
    //   Field type: int[], unsigned
    //   Offset (bits): 128
    //   Size of each element (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'lqi' is signed (false).
     */
    public static boolean isSigned_lqi() {
        return false;
    }

    /**
     * Return whether the field 'lqi' is an array (true).
     */
    public static boolean isArray_lqi() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'lqi'
     */
    public static int offset_lqi(int index1) {
        int offset = 128;
        if (index1 < 0 || index1 >= 4) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'lqi'
     */
    public static int offsetBits_lqi(int index1) {
        int offset = 128;
        if (index1 < 0 || index1 >= 4) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return offset;
    }

    /**
     * Return the entire array 'lqi' as a int[]
     */
    public int[] get_lqi() {
        int[] tmp = new int[4];
        for (int index0 = 0; index0 < numElements_lqi(0); index0++) {
            tmp[index0] = getElement_lqi(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'lqi' from the given int[]
     */
    public void set_lqi(int[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_lqi(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a int) of the array 'lqi'
     */
    public int getElement_lqi(int index1) {
        return (int)getUIntBEElement(offsetBits_lqi(index1), 16);
    }

    /**
     * Set an element of the array 'lqi'
     */
    public void setElement_lqi(int index1, int value) {
        setUIntBEElement(offsetBits_lqi(index1), 16, value);
    }

    /**
     * Return the total size, in bytes, of the array 'lqi'
     */
    public static int totalSize_lqi() {
        return (64 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'lqi'
     */
    public static int totalSizeBits_lqi() {
        return 64;
    }

    /**
     * Return the size, in bytes, of each element of the array 'lqi'
     */
    public static int elementSize_lqi() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'lqi'
     */
    public static int elementSizeBits_lqi() {
        return 16;
    }

    /**
     * Return the number of dimensions in the array 'lqi'
     */
    public static int numDimensions_lqi() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'lqi'
     */
    public static int numElements_lqi() {
        return 4;
    }

    /**
     * Return the number of elements in the array 'lqi'
     * for the given dimension.
     */
    public static int numElements_lqi(int dimension) {
      int array_dims[] = { 4,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

}
