/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'AgillaCodeMsg'
 * message type.
 */

package agilla.messages;

public class AgillaCodeMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 26;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 17;

    /** Create a new AgillaCodeMsg of size 26. */
    public AgillaCodeMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new AgillaCodeMsg of the given data_length. */
    public AgillaCodeMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AgillaCodeMsg with the given data_length
     * and base offset.
     */
    public AgillaCodeMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AgillaCodeMsg using the given byte array
     * as backing store.
     */
    public AgillaCodeMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AgillaCodeMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public AgillaCodeMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AgillaCodeMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public AgillaCodeMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AgillaCodeMsg embedded in the given message
     * at the given base offset.
     */
    public AgillaCodeMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AgillaCodeMsg embedded in the given message
     * at the given base offset and length.
     */
    public AgillaCodeMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <AgillaCodeMsg> \n";
      try {
        s += "  [id.id=0x"+Long.toHexString(get_id_id())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [msgNum=0x"+Long.toHexString(get_msgNum())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [code=";
        for (int i = 0; i < 22; i++) {
          s += "0x"+Long.toHexString(getElement_code(i) & 0xff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: id.id
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'id.id' is signed (false).
     */
    public static boolean isSigned_id_id() {
        return false;
    }

    /**
     * Return whether the field 'id.id' is an array (false).
     */
    public static boolean isArray_id_id() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'id.id'
     */
    public static int offset_id_id() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'id.id'
     */
    public static int offsetBits_id_id() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'id.id'
     */
    public int get_id_id() {
        return (int)getUIntBEElement(offsetBits_id_id(), 16);
    }

    /**
     * Set the value of the field 'id.id'
     */
    public void set_id_id(int value) {
        setUIntBEElement(offsetBits_id_id(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'id.id'
     */
    public static int size_id_id() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'id.id'
     */
    public static int sizeBits_id_id() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: msgNum
    //   Field type: int, unsigned
    //   Offset (bits): 16
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'msgNum' is signed (false).
     */
    public static boolean isSigned_msgNum() {
        return false;
    }

    /**
     * Return whether the field 'msgNum' is an array (false).
     */
    public static boolean isArray_msgNum() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'msgNum'
     */
    public static int offset_msgNum() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'msgNum'
     */
    public static int offsetBits_msgNum() {
        return 16;
    }

    /**
     * Return the value (as a int) of the field 'msgNum'
     */
    public int get_msgNum() {
        return (int)getUIntBEElement(offsetBits_msgNum(), 16);
    }

    /**
     * Set the value of the field 'msgNum'
     */
    public void set_msgNum(int value) {
        setUIntBEElement(offsetBits_msgNum(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'msgNum'
     */
    public static int size_msgNum() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'msgNum'
     */
    public static int sizeBits_msgNum() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: code
    //   Field type: short[], unsigned
    //   Offset (bits): 32
    //   Size of each element (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'code' is signed (false).
     */
    public static boolean isSigned_code() {
        return false;
    }

    /**
     * Return whether the field 'code' is an array (true).
     */
    public static boolean isArray_code() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'code'
     */
    public static int offset_code(int index1) {
        int offset = 32;
        if (index1 < 0 || index1 >= 22) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'code'
     */
    public static int offsetBits_code(int index1) {
        int offset = 32;
        if (index1 < 0 || index1 >= 22) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return offset;
    }

    /**
     * Return the entire array 'code' as a short[]
     */
    public short[] get_code() {
        short[] tmp = new short[22];
        for (int index0 = 0; index0 < numElements_code(0); index0++) {
            tmp[index0] = getElement_code(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'code' from the given short[]
     */
    public void set_code(short[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_code(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a short) of the array 'code'
     */
    public short getElement_code(int index1) {
        return (short)getUIntBEElement(offsetBits_code(index1), 8);
    }

    /**
     * Set an element of the array 'code'
     */
    public void setElement_code(int index1, short value) {
        setUIntBEElement(offsetBits_code(index1), 8, value);
    }

    /**
     * Return the total size, in bytes, of the array 'code'
     */
    public static int totalSize_code() {
        return (176 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'code'
     */
    public static int totalSizeBits_code() {
        return 176;
    }

    /**
     * Return the size, in bytes, of each element of the array 'code'
     */
    public static int elementSize_code() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'code'
     */
    public static int elementSizeBits_code() {
        return 8;
    }

    /**
     * Return the number of dimensions in the array 'code'
     */
    public static int numDimensions_code() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'code'
     */
    public static int numElements_code() {
        return 22;
    }

    /**
     * Return the number of elements in the array 'code'
     * for the given dimension.
     */
    public static int numElements_code(int dimension) {
      int array_dims[] = { 22,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /**
     * Fill in the array 'code' with a String
     */
    public void setString_code(String s) { 
         int len = s.length();
         int i;
         for (i = 0; i < len; i++) {
             setElement_code(i, (short)s.charAt(i));
         }
         setElement_code(i, (short)0); //null terminate
    }

    /**
     * Read the array 'code' as a String
     */
    public String getString_code() { 
         char carr[] = new char[Math.min(net.tinyos.message.Message.MAX_CONVERTED_STRING_LENGTH,22)];
         int i;
         for (i = 0; i < carr.length; i++) {
             if ((char)getElement_code(i) == (char)0) break;
             carr[i] = (char)getElement_code(i);
         }
         return new String(carr,0,i);
    }

}
