/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'AgillaTSReqMsg'
 * message type.
 */

package agilla.messages;

public class AgillaTSReqMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 28;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 48;

    /** Create a new AgillaTSReqMsg of size 28. */
    public AgillaTSReqMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new AgillaTSReqMsg of the given data_length. */
    public AgillaTSReqMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AgillaTSReqMsg with the given data_length
     * and base offset.
     */
    public AgillaTSReqMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AgillaTSReqMsg using the given byte array
     * as backing store.
     */
    public AgillaTSReqMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AgillaTSReqMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public AgillaTSReqMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AgillaTSReqMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public AgillaTSReqMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AgillaTSReqMsg embedded in the given message
     * at the given base offset.
     */
    public AgillaTSReqMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AgillaTSReqMsg embedded in the given message
     * at the given base offset and length.
     */
    public AgillaTSReqMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <AgillaTSReqMsg> \n";
      try {
        s += "  [dest=0x"+Long.toHexString(get_dest())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [reply=0x"+Long.toHexString(get_reply())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [op=0x"+Long.toHexString(get_op())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [dummy=0x"+Long.toHexString(get_dummy())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [template.flags=0x"+Long.toHexString(get_template_flags())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [template.size=0x"+Long.toHexString(get_template_size())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [template.data=";
        for (int i = 0; i < 20; i++) {
          s += "0x"+Long.toHexString(getElement_template_data(i) & 0xff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: dest
    //   Field type: int
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'dest' is signed (false).
     */
    public static boolean isSigned_dest() {
        return false;
    }

    /**
     * Return whether the field 'dest' is an array (false).
     */
    public static boolean isArray_dest() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'dest'
     */
    public static int offset_dest() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'dest'
     */
    public static int offsetBits_dest() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'dest'
     */
    public int get_dest() {
        return (int)getUIntBEElement(offsetBits_dest(), 16);
    }

    /**
     * Set the value of the field 'dest'
     */
    public void set_dest(int value) {
        setUIntBEElement(offsetBits_dest(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'dest'
     */
    public static int size_dest() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'dest'
     */
    public static int sizeBits_dest() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: reply
    //   Field type: int
    //   Offset (bits): 16
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'reply' is signed (false).
     */
    public static boolean isSigned_reply() {
        return false;
    }

    /**
     * Return whether the field 'reply' is an array (false).
     */
    public static boolean isArray_reply() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'reply'
     */
    public static int offset_reply() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'reply'
     */
    public static int offsetBits_reply() {
        return 16;
    }

    /**
     * Return the value (as a int) of the field 'reply'
     */
    public int get_reply() {
        return (int)getUIntBEElement(offsetBits_reply(), 16);
    }

    /**
     * Set the value of the field 'reply'
     */
    public void set_reply(int value) {
        setUIntBEElement(offsetBits_reply(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'reply'
     */
    public static int size_reply() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'reply'
     */
    public static int sizeBits_reply() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: op
    //   Field type: short
    //   Offset (bits): 32
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'op' is signed (false).
     */
    public static boolean isSigned_op() {
        return false;
    }

    /**
     * Return whether the field 'op' is an array (false).
     */
    public static boolean isArray_op() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'op'
     */
    public static int offset_op() {
        return (32 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'op'
     */
    public static int offsetBits_op() {
        return 32;
    }

    /**
     * Return the value (as a short) of the field 'op'
     */
    public short get_op() {
        return (short)getUIntBEElement(offsetBits_op(), 8);
    }

    /**
     * Set the value of the field 'op'
     */
    public void set_op(short value) {
        setUIntBEElement(offsetBits_op(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'op'
     */
    public static int size_op() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'op'
     */
    public static int sizeBits_op() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: dummy
    //   Field type: short
    //   Offset (bits): 40
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'dummy' is signed (false).
     */
    public static boolean isSigned_dummy() {
        return false;
    }

    /**
     * Return whether the field 'dummy' is an array (false).
     */
    public static boolean isArray_dummy() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'dummy'
     */
    public static int offset_dummy() {
        return (40 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'dummy'
     */
    public static int offsetBits_dummy() {
        return 40;
    }

    /**
     * Return the value (as a short) of the field 'dummy'
     */
    public short get_dummy() {
        return (short)getUIntBEElement(offsetBits_dummy(), 8);
    }

    /**
     * Set the value of the field 'dummy'
     */
    public void set_dummy(short value) {
        setUIntBEElement(offsetBits_dummy(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'dummy'
     */
    public static int size_dummy() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'dummy'
     */
    public static int sizeBits_dummy() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: template.flags
    //   Field type: short
    //   Offset (bits): 48
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'template.flags' is signed (false).
     */
    public static boolean isSigned_template_flags() {
        return false;
    }

    /**
     * Return whether the field 'template.flags' is an array (false).
     */
    public static boolean isArray_template_flags() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'template.flags'
     */
    public static int offset_template_flags() {
        return (48 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'template.flags'
     */
    public static int offsetBits_template_flags() {
        return 48;
    }

    /**
     * Return the value (as a short) of the field 'template.flags'
     */
    public short get_template_flags() {
        return (short)getUIntBEElement(offsetBits_template_flags(), 8);
    }

    /**
     * Set the value of the field 'template.flags'
     */
    public void set_template_flags(short value) {
        setUIntBEElement(offsetBits_template_flags(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'template.flags'
     */
    public static int size_template_flags() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'template.flags'
     */
    public static int sizeBits_template_flags() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: template.size
    //   Field type: short
    //   Offset (bits): 56
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'template.size' is signed (false).
     */
    public static boolean isSigned_template_size() {
        return false;
    }

    /**
     * Return whether the field 'template.size' is an array (false).
     */
    public static boolean isArray_template_size() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'template.size'
     */
    public static int offset_template_size() {
        return (56 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'template.size'
     */
    public static int offsetBits_template_size() {
        return 56;
    }

    /**
     * Return the value (as a short) of the field 'template.size'
     */
    public short get_template_size() {
        return (short)getUIntBEElement(offsetBits_template_size(), 8);
    }

    /**
     * Set the value of the field 'template.size'
     */
    public void set_template_size(short value) {
        setUIntBEElement(offsetBits_template_size(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'template.size'
     */
    public static int size_template_size() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'template.size'
     */
    public static int sizeBits_template_size() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: template.data
    //   Field type: short[]
    //   Offset (bits): 64
    //   Size of each element (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'template.data' is signed (false).
     */
    public static boolean isSigned_template_data() {
        return false;
    }

    /**
     * Return whether the field 'template.data' is an array (true).
     */
    public static boolean isArray_template_data() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'template.data'
     */
    public static int offset_template_data(int index1) {
        int offset = 64;
        if (index1 < 0 || index1 >= 20) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'template.data'
     */
    public static int offsetBits_template_data(int index1) {
        int offset = 64;
        if (index1 < 0 || index1 >= 20) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return offset;
    }

    /**
     * Return the entire array 'template.data' as a short[]
     */
    public short[] get_template_data() {
        short[] tmp = new short[20];
        for (int index0 = 0; index0 < numElements_template_data(0); index0++) {
            tmp[index0] = getElement_template_data(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'template.data' from the given short[]
     */
    public void set_template_data(short[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_template_data(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a short) of the array 'template.data'
     */
    public short getElement_template_data(int index1) {
        return (short)getUIntBEElement(offsetBits_template_data(index1), 8);
    }

    /**
     * Set an element of the array 'template.data'
     */
    public void setElement_template_data(int index1, short value) {
        setUIntBEElement(offsetBits_template_data(index1), 8, value);
    }

    /**
     * Return the total size, in bytes, of the array 'template.data'
     */
    public static int totalSize_template_data() {
        return (160 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'template.data'
     */
    public static int totalSizeBits_template_data() {
        return 160;
    }

    /**
     * Return the size, in bytes, of each element of the array 'template.data'
     */
    public static int elementSize_template_data() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'template.data'
     */
    public static int elementSizeBits_template_data() {
        return 8;
    }

    /**
     * Return the number of dimensions in the array 'template.data'
     */
    public static int numDimensions_template_data() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'template.data'
     */
    public static int numElements_template_data() {
        return 20;
    }

    /**
     * Return the number of elements in the array 'template.data'
     * for the given dimension.
     */
    public static int numElements_template_data(int dimension) {
      int array_dims[] = { 20,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /**
     * Fill in the array 'template.data' with a String
     */
    public void setString_template_data(String s) { 
         int len = s.length();
         int i;
         for (i = 0; i < len; i++) {
             setElement_template_data(i, (short)s.charAt(i));
         }
         setElement_template_data(i, (short)0); //null terminate
    }

    /**
     * Read the array 'template.data' as a String
     */
    public String getString_template_data() { 
         char carr[] = new char[Math.min(net.tinyos.message.Message.MAX_CONVERTED_STRING_LENGTH,20)];
         int i;
         for (i = 0; i < carr.length; i++) {
             if ((char)getElement_template_data(i) == (char)0) break;
             carr[i] = (char)getElement_template_data(i);
         }
         return new String(carr,0,i);
    }

}
