/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'AgillaExpLatencyMsg'
 * message type.
 */

package agilla.messages;

public class AgillaExpLatencyMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 4;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 145;

    /** Create a new AgillaExpLatencyMsg of size 4. */
    public AgillaExpLatencyMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new AgillaExpLatencyMsg of the given data_length. */
    public AgillaExpLatencyMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AgillaExpLatencyMsg with the given data_length
     * and base offset.
     */
    public AgillaExpLatencyMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AgillaExpLatencyMsg using the given byte array
     * as backing store.
     */
    public AgillaExpLatencyMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AgillaExpLatencyMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public AgillaExpLatencyMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AgillaExpLatencyMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public AgillaExpLatencyMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AgillaExpLatencyMsg embedded in the given message
     * at the given base offset.
     */
    public AgillaExpLatencyMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AgillaExpLatencyMsg embedded in the given message
     * at the given base offset and length.
     */
    public AgillaExpLatencyMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <AgillaExpLatencyMsg> \n";
      try {
        s += "  [latency=0x"+Long.toHexString(get_latency())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: latency
    //   Field type: long, unsigned
    //   Offset (bits): 0
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'latency' is signed (false).
     */
    public static boolean isSigned_latency() {
        return false;
    }

    /**
     * Return whether the field 'latency' is an array (false).
     */
    public static boolean isArray_latency() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'latency'
     */
    public static int offset_latency() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'latency'
     */
    public static int offsetBits_latency() {
        return 0;
    }

    /**
     * Return the value (as a long) of the field 'latency'
     */
    public long get_latency() {
        return (long)getUIntElement(offsetBits_latency(), 32);
    }

    /**
     * Set the value of the field 'latency'
     */
    public void set_latency(long value) {
        setUIntElement(offsetBits_latency(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'latency'
     */
    public static int size_latency() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'latency'
     */
    public static int sizeBits_latency() {
        return 32;
    }

}
