/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'AgillaTimeSyncMsg'
 * message type.
 */

package agilla.messages;

public class AgillaTimeSyncMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 8;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 80;

    /** Create a new AgillaTimeSyncMsg of size 8. */
    public AgillaTimeSyncMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new AgillaTimeSyncMsg of the given data_length. */
    public AgillaTimeSyncMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AgillaTimeSyncMsg with the given data_length
     * and base offset.
     */
    public AgillaTimeSyncMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AgillaTimeSyncMsg using the given byte array
     * as backing store.
     */
    public AgillaTimeSyncMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AgillaTimeSyncMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public AgillaTimeSyncMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AgillaTimeSyncMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public AgillaTimeSyncMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AgillaTimeSyncMsg embedded in the given message
     * at the given base offset.
     */
    public AgillaTimeSyncMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AgillaTimeSyncMsg embedded in the given message
     * at the given base offset and length.
     */
    public AgillaTimeSyncMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <AgillaTimeSyncMsg> \n";
      try {
        s += "  [time.high32=0x"+Long.toHexString(get_time_high32())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [time.low32=0x"+Long.toHexString(get_time_low32())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: time.high32
    //   Field type: long
    //   Offset (bits): 0
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'time.high32' is signed (false).
     */
    public static boolean isSigned_time_high32() {
        return false;
    }

    /**
     * Return whether the field 'time.high32' is an array (false).
     */
    public static boolean isArray_time_high32() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'time.high32'
     */
    public static int offset_time_high32() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'time.high32'
     */
    public static int offsetBits_time_high32() {
        return 0;
    }

    /**
     * Return the value (as a long) of the field 'time.high32'
     */
    public long get_time_high32() {
        return (long)getUIntBEElement(offsetBits_time_high32(), 32);
    }

    /**
     * Set the value of the field 'time.high32'
     */
    public void set_time_high32(long value) {
        setUIntBEElement(offsetBits_time_high32(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'time.high32'
     */
    public static int size_time_high32() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'time.high32'
     */
    public static int sizeBits_time_high32() {
        return 32;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: time.low32
    //   Field type: long
    //   Offset (bits): 32
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'time.low32' is signed (false).
     */
    public static boolean isSigned_time_low32() {
        return false;
    }

    /**
     * Return whether the field 'time.low32' is an array (false).
     */
    public static boolean isArray_time_low32() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'time.low32'
     */
    public static int offset_time_low32() {
        return (32 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'time.low32'
     */
    public static int offsetBits_time_low32() {
        return 32;
    }

    /**
     * Return the value (as a long) of the field 'time.low32'
     */
    public long get_time_low32() {
        return (long)getUIntBEElement(offsetBits_time_low32(), 32);
    }

    /**
     * Set the value of the field 'time.low32'
     */
    public void set_time_low32(long value) {
        setUIntBEElement(offsetBits_time_low32(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'time.low32'
     */
    public static int size_time_low32() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'time.low32'
     */
    public static int sizeBits_time_low32() {
        return 32;
    }

}
