# Top-level Makefile for tools/java 
TOS = $(shell ncc -print-tosdir)
#ROOT = ../../../../..
#ROOT = $(TOS)/../tools/java
ROOT = $(TOS)/../support/sdk/java
include $(ROOT)/Makefile.include

# List of message classes to build
MSGS = 

